# .github/dependabot.yml
version: 2
updates:
  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/" # Location of workflow files
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"

  # Keep NuGet dependencies up to date
  - package-ecosystem: "nuget"
    directory: "/" # Location of solution file
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "nuget"
