#---------------------------------# 
#      general configuration      # 
#---------------------------------# 
 
# version format 
version: 0.1-{build}

# branches to build
#branches

 
# Do not build on tags (GitHub only)
# This avoids the infinite build loop as Deploy to GitHub is set to create a tag each time.
skip_tags: true 

#---------------------------------# 
#    environment configuration    # 
#---------------------------------# 
 
# scripts that are called at very beginning, before repo cloning 
init:
- git config --global core.autocrlf input

# Automatically register private account and/or project AppVeyor NuGet feeds.
nuget:
    account_feed: true
    project_feed: true
    disable_publish_on_pr: true     # disable publishing of .nupkg artifacts to
                                    # account/project feeds for pull request builds

#---------------------------------# 
#       build configuration       # 
#---------------------------------# 
 
# build platform, i.e. x86, x64, Any CPU. This setting is optional. 
platform: Any CPU 

# build Configuration, i.e. Debug, Release, etc.
before_build:
    - cmd: nuget restore "Kajabity.Tools.Csv.sln"

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

build:
    publish_nuget: true             # package projects with .nuspec files and push to artifacts 
    publish_nuget_symbols: true     # generate and publish NuGet symbol packages 
    include_nuget_references: true  # add -IncludeReferencedProjects option while packaging NuGet artifacts 
 
# MSBuild verbosity level - one of quiet|minimal|normal|detailed
    verbosity: normal

#---------------------------------# 
#      artifacts configuration    # 
#---------------------------------# 
 
artifacts:
    - path: Kajabity.Tools.Csv\bin\$(configuration)\Kajabity.Tools.Csv.dll

      # Being more specific to avoid also identifying NUnit as an artefact.
    - path: Kajabity.Tools.Csv\bin\$(configuration)\*.nupkg

#---------------------------------# 
#     deployment configuration    # 
#---------------------------------# 

# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment 
# provider names are case-sensitive! 

deploy:

    # Deploying to NuGet feed
  - provider: NuGet
    api_key:
        secure: r3ybnECBTOpYHj0EtDF6FMn5V38UX6qrTrf3uRya2v/XlqEp8Qm0z3cK/1+hAQSm
    skip_symbols: false
    artifact: /.*\.nupkg/
    on:
        #appveyor_repo_tag: true        # deploy on tag push only - removed or won't deploy at all.
        branch: master                 # release from master branch only

    # Deploy to GitHub Releases 
  - provider: GitHub 
    release: kajabity.tools.csv-v$(appveyor_build_version)
    description: 'Kajabity.Tools.Csv Release v$(appveyor_build_version)'
    auth_token:
        secure: qyEhOXLpH0txl0uO1Y3k99DUnjxsF2bmZydo8h7g05/fyNs+uj/ge+Qg273TsVU1
    draft: false
    prerelease: false
    #appveyor_repo_tag: true        # deploy on tag push only
