# .github/workflows/dependabot-auto-merge.yml
name: Dependabot auto-merge

on:
  pull_request:
    branches: [ "main" ]

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v5

      - name: Auto-merge Dependabot PRs
        uses: fastify/github-action-merge-dependabot@v3
        with:
          target: minor
