name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: write
  packages: write

jobs:
  publish:
    name: Publish Release & NuGet
    runs-on: windows-latest   # required for .NET Framework builds

    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0

      - name: Restore dependencies
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build --configuration Release --no-restore

      - name: Pack NuGet package
        run: dotnet pack src/Kajabity.Tools.Csv/Kajabity.Tools.Csv.csproj --configuration Release --no-build -o ./artifacts

      - name: Publish to GitHub Packages
        run: dotnet nuget push **/artifacts/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --skip-duplicate

      - name: Publish to NuGet.org
        run: dotnet nuget push **/artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json  --skip-duplicate

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*.nupkg
